### ISSUE TITLE
build fails with toolchain 1.34

### ISSUE THREAD

**Issue by nnrepos** [PoDMR/enum-spanner-rs#3] opened 2021-05-06 10:08 UTC
since `memchr` version 2.4.0 was released 5 days ago, the build fails:

```
>cargo +1.34 install --git https://github.com/PoDMR/enum-spanner-rs/
...
Compiling bit-set v0.5.2
error[E0658]: naming constants with `_` is unstable (see issue #54912)
...
error: Could not compile `memchr`.
```

is there any quick fix? maybe change the dependencies somehow?
thanks

**Comment by a3nm** [comment] 2021-05-13 08:28
Hello,

I was able to reproduce this on a machine with an old version of Rust installed. However, reinstalling a more recent version of rust (the one from Debian testing) made the problem go away, and I have successfully compiled using:

```
patrocle:~/git/enum-spanner-rs$ cargo --version
cargo 1.46.0
patrocle:~/git/enum-spanner-rs$ rustc --version
rustc 1.48.0
```

However, while compilation has succeeded, there was a run error on the example from the README:

```
patrocle:~/git/enum-spanner-rs$ echo "aa@aa" | RUST_BACKTRACE=1 cargo run -- ".+@.+" 
    Finished dev [optimized + debuginfo] target(s) in 0.02s
     Running `target/debug/enum-spanner-rs '.+@.+'`
⠁ [=========================================]  00:00  488.28 Ki/s
⠁ [=========================================]  00:00  4.77 Mi/s
⠁ [=========================================]  00:00  697.54 Ki/s
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/matrix.rs:151:22
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:62
   3: enum_spanner_rs::matrix::Matrix::col_mul_inplace
             at ./src/matrix.rs:151
   4: enum_spanner_rs::mapping::jump::Jump::jump
             at ./src/mapping/jump.rs:200
   5: <enum_spanner_rs::mapping::indexed_dag::IndexedDagIterator as core::iter::traits::iterator::Iterator>::next
             at ./src/mapping/indexed_dag.rs:277
   6: <alloc::boxed::Box<I> as core::iter::traits::iterator::Iterator>::next
             at /usr/src/rustc-1.48.0/library/alloc/src/boxed.rs:976
   7: <core::iter::adapters::Enumerate<I> as core::iter::traits::iterator::Iterator>::next
             at /usr/src/rustc-1.48.0/library/core/src/iter/adapters/mod.rs:1374
   8: enum_spanner_rs::main::handle_matches
             at ./src/main.rs:307
   9: enum_spanner_rs::main
             at ./src/main.rs:345
  10: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running `cargo test` also doesn't work, so it does look like the code has "rusted" (no pun intended) since we last used it... Let us see what we can do.

**Comment by a3nm** [comment] 2021-05-13 09:04
Looking more into it: I can get the code to compile and run without that error with cargo and rustc from Debian buster:

```
patrocle:~/git/enum-spanner-rs$ rustc --version                                     
rustc 1.41.1                          
patrocle:~/git/enum-spanner-rs$ cargo --version
cargo 1.42.1
```

The tests (`cargo test`) still do not work, but I am not sure if they were working last time we used the code.

I am not sure yet about what breaks the code when moving to a newer rust, we should figure this out...

**Comment by nnrepos** [comment] 2021-05-16 11:25
my fix was adding `memchr = "=2.3.4"` inside `Cargo.toml`

**Comment by a3nm** [comment] 2021-05-17 14:26
Many thanks for confirming! That said, I think the proper fix should be using a newer Rust, so we should figure out the other problem I had found.

**Comment by a3nm** [comment] 2021-11-22 17:29
Checking again, I am still getting the same error on the example with a newer version of Rust:

```
$ cargo --version
cargo 1.56.0
$ rustc --version
rustc 1.56.0
$ echo "aa@aa" | RUST_BACKTRACE=1 cargo run -- ".+@.+"
    Finished dev [optimized + debuginfo] target(s) in 1m 19s
     Running `target/debug/enum-spanner-rs '.+@.+'`
⠁ [=========================================]  00:00  610.35 Ki/s
⠁ [=========================================]  00:00  4.77 Mi/s
⠁ [=========================================]  00:00  813.80 Ki/s
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/matrix.rs:151:22
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.56.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.56.0/library/core/src/panicking.rs:101:14
   2: core::panicking::panic_bounds_check
             at /usr/src/rustc-1.56.0/library/core/src/panicking.rs:77:5
   3: enum_spanner_rs::matrix::Matrix::col_mul_inplace
             at ./src/matrix.rs:151:22
   4: enum_spanner_rs::mapping::jump::Jump::jump
             at ./src/mapping/jump.rs:200:17
   5: <enum_spanner_rs::mapping::indexed_dag::IndexedDagIterator as core::iter::traits::iterator::Iterator>::next
             at ./src/mapping/indexed_dag.rs:277:50
   6: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /usr/src/rustc-1.56.0/library/alloc/src/boxed.rs:1570:9
   7: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::next
             at /usr/src/rustc-1.56.0/library/core/src/iter/adapters/enumerate.rs:46:17
   8: enum_spanner_rs::main::handle_matches
             at ./src/main.rs:307:41
   9: enum_spanner_rs::main
             at ./src/main.rs:345:30
  10: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.56.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by niewerth** [comment] 2021-11-26 09:00
The problem should be solved in the master branch. The error was to check the capacity of a BitSet instead of the length. Of course, the allocation is the size of the capacity. Nevertheless the underlying vector panics if we access allocated but potentially not initialized members of the BitSet.

In earlier Rust versions, it seems that the BitSet was never created with len != capacity. At lest the error did never show up in our tests.

P.S.: Sorry for the very late reply. I was completely overworked with teaching due to corona.

**Closed as completed by niewerth** 2021-11-26 09:00 UTC

**Comment by a3nm** [comment] 2021-11-26 11:02
Thanks Matthias! I confirm that this also fixes the problem for me.
